"use client";

import { useEffect, useLayoutEffect, useRef, useState } from "react";

/** A Letter page is 8.5in × 11in, which is 816 × 1056 CSS pixels at 96dpi. */
const PAGE_W = 816;
const PAGE_H = 1056;

/**
 * Shows a full Letter page scaled down to fit its container.
 *
 * The HTML comes from the same template that renders the PDF, dropped into an
 * iframe so the voucher's own styles stay completely isolated from the portal's.
 */
export default function SheetPreview({
  html,
  busy,
}: {
  html: string;
  busy?: boolean;
}) {
  const holder = useRef<HTMLDivElement>(null);
  const [scale, setScale] = useState(0.5);

  // Track the container width and scale the page to match it.
  useLayoutEffect(() => {
    const el = holder.current;
    if (!el) return;
    const measure = () => setScale(el.clientWidth / PAGE_W);
    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  return (
    <div
      ref={holder}
      className="relative w-full overflow-hidden rounded-lg border border-ink-line bg-white"
      style={{ height: PAGE_H * scale }}
    >
      <iframe
        title="Voucher preview"
        // The preview HTML is generated by our own template on the server.
        srcDoc={html}
        // No allow-scripts, so nothing in here can execute. allow-same-origin is
        // needed because @font-face requests are CORS-checked, and an opaque
        // origin would make the bundled fonts fail to load.
        sandbox="allow-same-origin"
        scrolling="no"
        className="sheet-scale absolute left-0 top-0 border-0"
        style={{ width: PAGE_W, height: PAGE_H, transform: `scale(${scale})` }}
      />
      {busy ? (
        /* Bottom-right: the voucher's own header sits at the top of the sheet. */
        <div className="pointer-events-none absolute bottom-2.5 right-2.5 rounded-full bg-white/90 px-2.5 py-1 text-[11px] font-medium text-ink-soft shadow-sm">
          Updating…
        </div>
      ) : null}
    </div>
  );
}

/**
 * Debounced live preview. Posts the current field values to /api/preview and
 * returns the rendered HTML, so the preview can never drift from the PDF.
 */
export function usePreview(company: string, fields: unknown, delay = 350) {
  const [html, setHtml] = useState("");
  const [busy, setBusy] = useState(true);
  const serialized = JSON.stringify(fields);

  useEffect(() => {
    setBusy(true);
    const controller = new AbortController();
    const timer = setTimeout(async () => {
      try {
        const res = await fetch("/api/preview", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ company, fields: JSON.parse(serialized) }),
          signal: controller.signal,
        });
        if (res.ok) setHtml(await res.text());
      } catch {
        // Aborted by the next keystroke, or offline — keep showing the last render.
      } finally {
        setBusy(false);
      }
    }, delay);

    return () => {
      clearTimeout(timer);
      controller.abort();
    };
  }, [company, serialized, delay]);

  return { html, busy };
}
