"use client";

import { useEffect, useLayoutEffect, useRef, useState } from "react";

/** A Letter page is 8.5in × 11in, which is 816 × 1056 CSS pixels at 96dpi. */
const PAGE_W = 816;
const PAGE_H = 1056;

/**
 * Shows a full Letter page scaled down to fit its container.
 *
 * The HTML comes from the same template that renders the PDF, dropped into an
 * iframe so the voucher's own styles stay completely isolated from the portal's.
 */
export default function SheetPreview({
  html,
  busy,
  width = PAGE_W,
  height = PAGE_H,
}: {
  html: string;
  busy?: boolean;
  /** Overrides the Letter-shaped default — a notification card is 360×450. */
  width?: number;
  height?: number;
}) {
  const holder = useRef<HTMLDivElement>(null);
  const [scale, setScale] = useState(0.5);

  // Track the container width and scale the page to match it.
  useLayoutEffect(() => {
    const el = holder.current;
    if (!el) return;
    const measure = () => setScale(el.clientWidth / width);
    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(el);
    return () => observer.disconnect();
  }, [width]);

  return (
    <div
      ref={holder}
      // bg-white, not bg-card: this is the sheet showing through, and a sheet is
      // white in both themes — nobody is printing the voucher on black paper.
      // The border stays the portal's, which is what frames the page against a
      // dark screen.
      className="relative w-full overflow-hidden rounded-lg border border-ink-line bg-white"
      style={{ height: height * scale }}
    >
      <iframe
        title="Document preview"
        // The preview HTML is generated by our own template on the server.
        srcDoc={html}
        // No allow-scripts, so nothing in here can execute. allow-same-origin is
        // needed because @font-face requests are CORS-checked, and an opaque
        // origin would make the bundled fonts fail to load.
        sandbox="allow-same-origin"
        scrolling="no"
        className="sheet-scale absolute left-0 top-0 border-0"
        style={{ width, height, transform: `scale(${scale})` }}
      />
      {/* Bottom-right: the voucher's own header sits at the top of the sheet.
          Always mounted and faded by opacity, rather than added/removed, so
          each debounced re-render doesn't pop the badge in and out.

          on-paper because this sits on the sheet rather than on the portal: the
          page underneath is white in both themes, so the badge's grey has to be
          the paper's grey and not the interface's, which in the dark theme is a
          pale one and would be invisible here. */}
      <div
        aria-hidden={!busy}
        className={`on-paper pointer-events-none absolute bottom-2.5 right-2.5 rounded-full bg-white/90 px-2.5 py-1 text-[11px] font-medium text-ink-soft shadow-sm transition-opacity duration-200 ${
          busy ? "opacity-100" : "opacity-0"
        }`}
      >
        Updating…
      </div>
    </div>
  );
}

/**
 * The same thing for a document that runs to more than one page: every page
 * stacked in a scrollable column, numbered, so the operator can see exactly
 * where the fold lands before anything is printed.
 */
export function SheetStack({
  pages,
  busy,
  maxHeight = "72vh",
}: {
  pages: string[];
  busy?: boolean;
  maxHeight?: string;
}) {
  if (pages.length === 0) {
    return (
      // Not paper: there is no sheet yet. Until one arrives this is a piece of
      // the portal saying so, and it takes the portal's colours.
      <div className="grid h-64 w-full place-items-center rounded-lg border border-ink-line bg-card text-[13px] text-ink-soft">
        Preparing preview…
      </div>
    );
  }

  return (
    <div className="relative">
      <div className="space-y-3 overflow-y-auto pr-0.5" style={{ maxHeight }}>
        {pages.map((html, i) => (
          <div key={i}>
            <SheetPreview html={html} />
            {pages.length > 1 ? (
              <div className="mono mt-1 text-center text-[11px] text-ink-soft">
                Page {i + 1} of {pages.length}
              </div>
            ) : null}
          </div>
        ))}
      </div>
      <div
        aria-hidden={!busy}
        className={`on-paper pointer-events-none absolute bottom-2.5 right-3.5 rounded-full bg-white/90 px-2.5 py-1 text-[11px] font-medium text-ink-soft shadow-sm transition-opacity duration-200 ${
          busy ? "opacity-100" : "opacity-0"
        }`}
      >
        Updating…
      </div>
    </div>
  );
}

/**
 * Debounced live preview. Posts the current field values to `endpoint` and
 * returns the rendered HTML, so the preview can never drift from the PDF.
 *
 * `endpoint` defaults to the voucher's /api/preview; other document types
 * pass their own, the same reasoning usePagesPreview below already gives.
 * `rejected` mirrors usePagesPreview's 422 handling, for document types (like
 * notifications) whose fields carry a length limit the preview route enforces.
 */
export function usePreview(
  company: string,
  fields: unknown,
  delay = 350,
  endpoint = "/api/preview",
) {
  const [html, setHtml] = useState("");
  const [busy, setBusy] = useState(true);
  const [rejected, setRejected] = useState<string | null>(null);
  const serialized = JSON.stringify(fields);

  useEffect(() => {
    setBusy(true);
    const controller = new AbortController();
    const timer = setTimeout(async () => {
      try {
        const res = await fetch(endpoint, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ company, fields: JSON.parse(serialized) }),
          signal: controller.signal,
        });
        if (res.ok) {
          setHtml(await res.text());
          setRejected(null);
        } else if (res.status === 422) {
          const body = (await res.json().catch(() => null)) as { error?: string } | null;
          setRejected(body?.error ?? "That cannot be previewed.");
        }
      } catch {
        // Aborted by the next keystroke, or offline — keep showing the last render.
      } finally {
        setBusy(false);
      }
    }, delay);

    return () => {
      clearTimeout(timer);
      controller.abort();
    };
  }, [company, serialized, delay, endpoint]);

  return { html, busy, rejected };
}

/**
 * The multi-page equivalent, for purchase orders and requests for quotation.
 *
 * A longer debounce than the voucher's: these renders are several pages of
 * layout and the operator is typically typing a whole line item, not tweaking
 * one word. The endpoint is a parameter because each document type validates and
 * renders its own payload.
 */
export function usePagesPreview(
  body: unknown,
  delay = 500,
  endpoint = "/api/po/preview",
) {
  const [pages, setPages] = useState<string[]>([]);
  const [busy, setBusy] = useState(true);
  /**
   * A value the server refuses to render — a description past its length limit.
   * Reported while typing rather than discovered on save, since the same parser
   * guards both and would refuse the save for the same reason.
   */
  const [rejected, setRejected] = useState<string | null>(null);
  const serialized = JSON.stringify(body);

  useEffect(() => {
    setBusy(true);
    const controller = new AbortController();
    const timer = setTimeout(async () => {
      try {
        const res = await fetch(endpoint, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: serialized,
          signal: controller.signal,
        });
        if (res.ok) {
          setPages(((await res.json()) as { pages: string[] }).pages);
          setRejected(null);
        } else if (res.status === 422) {
          const body = (await res.json().catch(() => null)) as { error?: string } | null;
          setRejected(body?.error ?? "That order cannot be previewed.");
        }
      } catch {
        // Aborted by the next keystroke, or offline — keep the last render.
      } finally {
        setBusy(false);
      }
    }, delay);

    return () => {
      clearTimeout(timer);
      controller.abort();
    };
  }, [serialized, delay, endpoint]);

  return { pages, busy, rejected };
}
